apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-ml-obs-ref-arch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/awslabs/ai-ml-observability-reference-architecture.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated: {}
