apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nim-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: k8s-nim-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: "v1.0.1"
  destination:
    server: https://kubernetes.default.svc
    namespace: nim-operator
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated: {}
